version: '2'

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "sadeeque"
            MONGO_INITDB_ROOT_PASSWORD: "secret"
            MONGO_INITDB_DATABASE: "keks"
        networks:
            - lexclassnet
    api:
        image: sadeeque/lexapi:v1.0
        restart: always
        ports:
            - "3000:3000"
        networks:
            - lexclassnet
networks:
    lexclassnet:
        driver: bridge